# Generated by Django 3.1.12 on 2021-07-07 06:59

from django.db import migrations, models
import twitter_clone.tweets.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, validators=[twitter_clone.tweets.validators.validate_f_word])),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=150, validators=[twitter_clone.tweets.validators.validate_f_word])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_retweet', models.BooleanField(default=False)),
                ('hashtags', models.ManyToManyField(blank=True, to='tweets.Hashtag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
