# Generated by Django 3.1.12 on 2021-07-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20210704_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='tweets.HashTag'),
        ),
    ]
